### ISSUE TITLE
Whitespace ignored in pre element

### ISSUE THREAD

**Issue by fivefilters** [layershifter/GumboPHP#7]
First of all, thanks a lot for Gumbo PHP! It's very useful!

I noticed what looks like a bug in the handling of the `pre` element where whitespace is important and should be preserved. Here's code to reproduce:

```
<?php
$whitespace_test =
'<html><body><pre>
<span>Line 1</span>
    <span>Line 2</span>
<span>Line 3</span>
</pre>
<pre>
Line 1
    Line 2
Line 3
</pre></body></html>';

// Gumbo PHP
$doc = \Layershifter\Gumbo\Parser::load($whitespace_test);
echo $doc->saveHTML();

// Regular DOMDocument
$doc = new DOMDocument();
$doc->loadHTML($whitespace_test, LIBXML_HTML_NODEFDTD);
echo $doc->saveHTML();
```

Gumbo PHP outputs:

```
<html><body><pre><span>Line 1</span><span>Line 2</span><span>Line 3</span></pre><pre>Line 1
    Line 2
Line 3
</pre></body></html>
```

Regular DOMDocument outputs:

```
<html><body><pre>
<span>Line 1</span>
    <span>Line 2</span>
<span>Line 3</span>
</pre>
<pre>
Line 1
    Line 2
Line 3
</pre></body></html>
```

I noticed there's a section related to whitespace commented out in [parser.c](https://github.com/layershifter/gumbo-php/blob/d61c16badd3a6981ccc1bee7e74f3f0b0eb3555b/src/parser.c#L113), could that be what's causing this? And if so, is it safe to uncomment it?

Any help appreciated. Thanks!

**Comment by layershifter** [comment]
@fivefilters Hi, thanks :smile: 

Yes, this can be uncommented and it will be the easiest solution. But as LibXML/PHP DOM doesn't have a special object for whitespaces i.e. `DOMWhitespace` it will produce too many unnessary `DOMText`'s. This will break my production app.

However, whitespaces should be always created when they are inside the `<pre>` tag. I'm think that I will able to fix it on this week. The provided test case is very usefull.

----

I'm also want to deprecate this package when [`php-myhtml`](https://github.com/layershifter/php-myhtml) will be production ready. But it needs too many time because there are complicated problems with inheritance of internal DOM classes. I'm not sure that I will be able to find it in this year.

**Comment by fivefilters** [comment]
@layershifter Thanks for the helpful reply! I'll wait for the fix. :)

Oh, and I didn't know about your myhtml extension for PHP. I'll be keeping an eye on that too.

**Comment by layershifter** [comment]
@fivefilters I've pushed recently [`d61c16b`](https://github.com/layershifter/gumbo-php/commit/137264b155268d4c7dcdea77b7eec4452d5e75c4), as you can see your test case was simplified. There is still problem with handling of new lines, but it's everything that I can do right now.

I'm planning to solve similar issues in `php-myhtml`, but as I said this will not be soon.

**Comment by fivefilters** [comment]
@layershifter Thank you! :)

**Comment by layershifter** [comment]
@fivefilters I know that you forked it, feel free to maintain it.

I'm working with frontend now and don't have enought time to work on it. I will archive this repo, if you have any questions - feel free to email me.
